
package com.chathurangaonline.jaxws.samples.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorServiceImpl", targetNamespace = "http://impl.samples.jaxws.chathurangaonline.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://impl.samples.jaxws.chathurangaonline.com/", className = "com.chathurangaonline.jaxws.samples.impl.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://impl.samples.jaxws.chathurangaonline.com/", className = "com.chathurangaonline.jaxws.samples.impl.MultiplyResponse")
    @Action(input = "http://impl.samples.jaxws.chathurangaonline.com/CalculatorServiceImpl/multiplyRequest", output = "http://impl.samples.jaxws.chathurangaonline.com/CalculatorServiceImpl/multiplyResponse")
    public double multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://impl.samples.jaxws.chathurangaonline.com/", className = "com.chathurangaonline.jaxws.samples.impl.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://impl.samples.jaxws.chathurangaonline.com/", className = "com.chathurangaonline.jaxws.samples.impl.AddResponse")
    @Action(input = "http://impl.samples.jaxws.chathurangaonline.com/CalculatorServiceImpl/addRequest", output = "http://impl.samples.jaxws.chathurangaonline.com/CalculatorServiceImpl/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
